# Generated by Django 3.1.5 on 2021-05-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdultoMayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(blank=True, max_length=200, null=True)),
                ('check_fechanacimiento', models.BooleanField()),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('lugarnacimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado_civil', models.CharField(choices=[('-', '-'), ('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Separado', 'Separado'), ('Divorciado', 'Divorciado'), ('Unión Libre', 'Unión Libre'), ('Ninguno', 'Ninguno'), ('Se rehúsa', 'Se rehúsa')], max_length=100)),
                ('ocupacion', models.CharField(choices=[('Inactivo(a)', 'Inactivo(a)'), ('Jubilado(a) sin pensión', 'Jubilado(a) sin pensión'), ('Jubilado(a) con pensión', 'Jubilado(a) con pensión'), ('Comercio informal', 'Comercio informal'), ('Jornalero/campesino', 'Jornalero/campesino'), ('Obrero(a)', 'Obrero(a)'), ('Empleado(a) de oficina', 'Empleado(a) de oficina'), ('Profesionista independiente', 'Profesionista independiente'), ('Patrón(a)/jefe/empresario(a)', 'Patrón(a)/jefe/empresario(a)'), ('Ama de casa', 'Ama de casa'), ('Desempleado(a)', 'Desempleado(a)'), ('Ninguno', 'Ninguno'), ('Se rehúsa', 'Se rehúsa')], max_length=100)),
                ('ocupacion_anterior', models.CharField(choices=[('Inactivo(a)', 'Inactivo(a)'), ('Jubilado(a) sin pensión', 'Jubilado(a) sin pensión'), ('Jubilado(a) con pensión', 'Jubilado(a) con pensión'), ('Comercio informal', 'Comercio informal'), ('Jornalero/campesino', 'Jornalero/campesino'), ('Obrero(a)', 'Obrero(a)'), ('Empleado(a) de oficina', 'Empleado(a) de oficina'), ('Profesionista independiente', 'Profesionista independiente'), ('Patrón(a)/jefe/empresario(a)', 'Patrón(a)/jefe/empresario(a)'), ('Ama de casa', 'Ama de casa'), ('Desempleado(a)', 'Desempleado(a)'), ('Ninguno', 'Ninguno'), ('Se rehúsa', 'Se rehúsa')], max_length=100)),
                ('seguridad_social', models.CharField(choices=[('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE'), ('SEDENA', 'SEDENA'), ('SEMAR', 'SEMAR'), ('PEMEX', 'PEMEX'), ('SSP-DF', 'SSP-DF'), ('INSABI', 'INSABI'), ('PRIVADO', 'PRIVADO'), ('GASTOS MÉDICOS MAYORES', 'GASTOS MÉDICOS MAYORES'), ('OTRO', 'OTRO')], max_length=100)),
                ('seguridad_social_otro', models.CharField(blank=True, max_length=100, null=True)),
                ('utiliza_seguridad_social', models.BooleanField()),
                ('acompanante', models.CharField(choices=[('Pareja', 'Pareja'), ('Hijos', 'Hijos'), ('Otro Familiar', 'Otro Familiar'), ('No Familiar', 'No Familiar'), ('Solo', 'Solo'), ('No se puede documentar', 'No se puede documentar'), ('Se rehúsa', 'Se rehúsa')], max_length=100)),
                ('acompanante_otro', models.CharField(blank=True, max_length=100, null=True)),
                ('acompanante_sexo', models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50, null=True)),
                ('check_acompanante_edad', models.BooleanField(blank=True, null=True)),
                ('acompanante_edad', models.IntegerField(blank=True, null=True)),
                ('check_cuidador', models.BooleanField()),
                ('cuidador', models.CharField(blank=True, choices=[('Pareja', 'Pareja'), ('Hijos', 'Hijos'), ('Otro Familiar', 'Otro Familiar'), ('No Familiar', 'No Familiar'), ('Formal(encargado del AM, Ej. Enfermera)', 'Formal(encargado del AM, Ej. Enfermera)'), ('Ninguno', 'Ninguno'), ('No sabe', 'No sabe'), ('No contesta', 'No contesta')], max_length=100, null=True)),
                ('cuidador_otro', models.CharField(blank=True, max_length=100, null=True)),
                ('cuidador_sexo', models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50, null=True)),
                ('check_cuidador_edad', models.BooleanField(blank=True, null=True)),
                ('cuidador_edad', models.IntegerField(blank=True, null=True)),
                ('nombres_profesional', models.CharField(max_length=200)),
                ('apellido_paterno_profesional', models.CharField(max_length=200)),
                ('apellido_materno_profesional', models.CharField(max_length=200)),
                ('fechaevaluacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=200, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido materno')),
                ('tipo_contratacion', models.CharField(choices=[('Estructura', 'Estructura'), ('Nomina 8', 'Nomina 8'), ('Honorarios', 'Honorarios'), ('Base con digito sindical', 'Base con digito sindical'), ('Base sin digito sindical', 'Base sin digito sindical')], max_length=50, verbose_name='Tipo de contratación')),
                ('numero_empleado', models.PositiveIntegerField(verbose_name='Número de empleado')),
                ('tipo_usuario', models.CharField(choices=[('Administrador', 'Administrador'), ('Monitor', 'Monitor'), ('Supervisor de módulo', 'Supervisor de módulo'), ('Personal de módulo', 'Personal de módulo')], max_length=21, verbose_name='Tipo de usuario')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('numero_telefonico', models.CharField(max_length=15, verbose_name='Número telefónico')),
                ('foto', models.ImageField(blank=True, default='guest.png', upload_to='', verbose_name='Sube una fotografía')),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
