# Generated by Django 3.1.5 on 2021-05-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=200, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido materno')),
                ('tipo_contratacion', models.CharField(max_length=50, verbose_name='Tipo de contratación')),
                ('numero_empleado', models.PositiveIntegerField(verbose_name='Número de empleado')),
                ('tipo_usuario', models.CharField(choices=[('Administrador', 'Administrador'), ('Monitor', 'Monitor'), ('Supervisor de módulo', 'Supervisor de módulo'), ('Personal de módulo', 'Personal de módulo')], max_length=21, verbose_name='Tipo de usuario')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('numero_telefonico', models.CharField(max_length=15, verbose_name='Número telefónico')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sube una fotografía')),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
