# Generated by Django 3.1.5 on 2021-05-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INED_app', '0002_auto_20210504_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Sube una fotografía'),
        ),
    ]
