# Generated by Django 3.1.5 on 2021-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INED_app', '0004_auto_20210504_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='guest.png', upload_to='', verbose_name='Sube una fotografía'),
        ),
    ]
