# Generated by Django 3.1.5 on 2021-05-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INED_app', '0006_auto_20210515_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultoMayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(blank=True, max_length=200, null=True)),
                ('check_fechanacimiento', models.BooleanField()),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=50)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('estado_civil', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('ocupacion_anterior', models.CharField(max_length=100)),
                ('seguridad_social', models.CharField(max_length=100)),
                ('utiliza_seguridad_social', models.BooleanField()),
                ('check_vive_solo', models.BooleanField()),
                ('acompanante', models.CharField(blank=True, max_length=100, null=True)),
                ('acompanante_sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('check_acompanante_fechanacimiento', models.BooleanField(blank=True, null=True)),
                ('acompanante_fechanacimiento', models.DateField(blank=True, null=True)),
                ('check_cuidador', models.BooleanField()),
                ('cuidador', models.CharField(blank=True, max_length=100, null=True)),
                ('cuidador_sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('check_cuidador_fechanacimiento', models.DateField(blank=True, null=True)),
                ('cuidador_fechanacimiento', models.DateField(blank=True, null=True)),
                ('nombres_profesional', models.CharField(max_length=200)),
                ('apellido_paterno_profesional', models.CharField(max_length=200)),
                ('apellido_materno_profesional', models.CharField(max_length=200)),
                ('fechaevaluacion', models.DateField()),
            ],
        ),
    ]
