# Generated by Django 3.1.5 on 2021-05-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INED_app', '0007_adultomayor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adultomayor',
            old_name='check_acompanante_fechanacimiento',
            new_name='check_acompanante_edad',
        ),
        migrations.RemoveField(
            model_name='adultomayor',
            name='acompanante_fechanacimiento',
        ),
        migrations.RemoveField(
            model_name='adultomayor',
            name='check_cuidador_fechanacimiento',
        ),
        migrations.RemoveField(
            model_name='adultomayor',
            name='check_vive_solo',
        ),
        migrations.RemoveField(
            model_name='adultomayor',
            name='cuidador_fechanacimiento',
        ),
        migrations.AddField(
            model_name='adultomayor',
            name='acompanante_edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adultomayor',
            name='acompanante_otro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adultomayor',
            name='check_cuidador_edad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adultomayor',
            name='cuidador_edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adultomayor',
            name='cuidador_otro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adultomayor',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='adultomayor',
            name='lugarnacimiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adultomayor',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='adultomayor',
            name='seguridad_social_otro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adultomayor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='acompanante',
            field=models.CharField(blank=True, choices=[('Pareja', 'Pareja'), ('Hijos', 'Hijos'), ('Otro Familiar', 'Otro Familiar'), ('No Familiar', 'No Familiar'), ('Solo', 'Solo'), ('No se puede documentar', 'No se puede documentar'), ('Se rehúsa', 'Se rehúsa')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='acompanante_sexo',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='cuidador',
            field=models.CharField(blank=True, choices=[('Pareja', 'Pareja'), ('Hijos', 'Hijos'), ('Otro Familiar', 'Otro Familiar'), ('No Familiar', 'No Familiar'), ('Formal(encargado del AM, Ej. Enfermera)', 'Formal(encargado del AM, Ej. Enfermera)'), ('Ninguno', 'Ninguno'), ('No sabe', 'No sabe'), ('No contesta', 'No contesta')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='cuidador_sexo',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='estado_civil',
            field=models.CharField(choices=[('-', '-'), ('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Separado', 'Separado'), ('Divorciado', 'Divorciado'), ('Unión Libre', 'Unión Libre'), ('Ninguno', 'Ninguno'), ('Se rehúsa', 'Se rehúsa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='ocupacion',
            field=models.CharField(choices=[('Inactivo(a)', 'Inactivo(a)'), ('Jubilado(a) sin pensión', 'Jubilado(a) sin pensión'), ('Jubilado(a) con pensión', 'Jubilado(a) con pensión'), ('Comercio informal', 'Comercio informal'), ('Jornalero/campesino', 'Jornalero/campesino'), ('Obrero(a)', 'Obrero(a)'), ('Empleado(a) de oficina', 'Empleado(a) de oficina'), ('Profesionista independiente', 'Profesionista independiente'), ('Patrón(a)/jefe/empresario(a)', 'Patrón(a)/jefe/empresario(a)'), ('Ama de casa', 'Ama de casa'), ('Desempleado(a)', 'Desempleado(a)'), ('Ninguno', 'Ninguno'), ('Se rehúsa', 'Se rehúsa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='ocupacion_anterior',
            field=models.CharField(choices=[('Inactivo(a)', 'Inactivo(a)'), ('Jubilado(a) sin pensión', 'Jubilado(a) sin pensión'), ('Jubilado(a) con pensión', 'Jubilado(a) con pensión'), ('Comercio informal', 'Comercio informal'), ('Jornalero/campesino', 'Jornalero/campesino'), ('Obrero(a)', 'Obrero(a)'), ('Empleado(a) de oficina', 'Empleado(a) de oficina'), ('Profesionista independiente', 'Profesionista independiente'), ('Patrón(a)/jefe/empresario(a)', 'Patrón(a)/jefe/empresario(a)'), ('Ama de casa', 'Ama de casa'), ('Desempleado(a)', 'Desempleado(a)'), ('Ninguno', 'Ninguno'), ('Se rehúsa', 'Se rehúsa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='seguridad_social',
            field=models.CharField(choices=[('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE'), ('SEDENA', 'SEDENA'), ('SEMAR', 'SEMAR'), ('PEMEX', 'PEMEX'), ('SSP-DF', 'SSP-DF'), ('INSABI', 'INSABI'), ('PRIVADO', 'PRIVADO'), ('GASTOS MÉDICOS MAYORES', 'GASTOS MÉDICOS MAYORES'), ('OTRO', 'OTRO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50),
        ),
    ]
